# Generated by Django 4.2.11 on 2024-04-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('tf', models.FloatField()),
                ('idf', models.FloatField()),
                ('count', models.IntegerField()),
            ],
            options={
                'ordering': ['-tf'],
            },
        ),
    ]
